name: Inkspire Backend CI
"on":
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - name: Clean up stale Git lock files
        run: |
          if [ -f .git/index.lock ]; then
            echo "Removing stale Git lock file..."
            rm -f .git/index.lock
          fi
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: Verify action integrity
        run: >
          echo "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
          actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb" | sha256sum

      # - name: Debug workspace
      #   run: |
      #     ls -la
      #     cd server
      #     ls -la

      # - name: "Use Node.js ${{ matrix.node-version }}"
      #   uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
      #   with:
      #     node-version: "${{ matrix.node-version }}"
      #     cache: "pnpm"
      #     cache-dependency-path: server/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env file
        run: |
          cd server
          touch .env
          echo "${{ secrets.PROD }}" > .env

      - name: Build project
        run: cd server && pnpm build

      - name: Start project with PM2
        run: cd server && pm2 reload server
